# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # === KEYBOARD HALVES ===
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view

  # === XIAO BLE DONGLE ===
  - board: xiao_ble
    shield: splitkb_aurora_corne_dongle_xiao

  # === SETTINGS RESET ===
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano@2.0.0
    shield: settings_reset
