# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # === KEYBOARD HALVES (STANDALONE MODE) ===
  # Left half acts as central, connects directly to host
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view

  # === KEYBOARD HALVES (DONGLE MODE) ===
  # Both halves are peripherals, connecting to the dongle
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: splitkb_aurora_corne_left_peripheral-nice_nano

  # === XIAO BLE DONGLE ===
  # Named 'corne_dongle' to avoid prefix matching with keyboard config files
  - board: xiao_ble
    shield: corne_dongle

  # === SETTINGS RESET ===
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano@2.0.0
    shield: settings_reset
