# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # === DONGLE MODE (use with XIAO BLE dongle) ===
  # Dongle (XIAO BLE as central - connects to both halves + computer via USB)
  - board: xiao_ble
    shield: aurora_corne_dongle_xiao

  # Left half (peripheral - connects to dongle)
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # Right half (peripheral - connects to dongle)
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view

  # === USB MODE (direct USB connection without dongle) ===
  # Left half (central - connects to right half + computer via USB)
  - board: nice_nano@2.0.0
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view

  # Right half (peripheral - connects to left half) - same firmware as dongle mode
  # No need to rebuild - use the firmware from dongle mode section above

  # === SETTINGS RESET ===
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano@2.0.0
    shield: settings_reset
